spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8189

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization