spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://mlmpiimwefjnhs:6deb02c19dac74b489d7fa3345f00311d84e78cb1017825c07d4981ea390b95f@ec2-52-30-67-143.eu-west-1.compute.amazonaws.com:5432/dc5ot1o0a24ckg
    username: mlmpiimwefjnhs
    password: 6deb02c19dac74b489d7fa3345f00311d84e78cb1017825c07d4981ea390b95f
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8189}

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization

